name: "py-style"
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

jobs:
    python-ubuntu:
      name: "formatting and typechecks"
      runs-on: "ubuntu-latest"
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |-
            python3 -m pip install black isort pytype
      - name: "Formatting checks: black, isort"
        run: |
            python3 -m black --check bindings/python/ setup.py
            python3 -m isort --profile black --diff --check bindings/python setup.py
      - name: "Static typing checks: pytype"
        run: |-
            python3 -m pytype bindings/python
