name: "py-style"
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - '**'

jobs:
    python-ubuntu:
      name: "isort, black"
      runs-on: "ubuntu-latest"
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |-
            python3 -m pip install black isort
      - name: Run check for formatting using black
        run: |
            python3 -m black --check bindings/python/ setup.py
            python3 -m isort --profile black --diff --check bindings/python setup.py
